#!/bin/bash
#
# If -aux is provided, the expected AuxDB entry ends up in the output.
#
. $(dirname $0)/common

run_aux -json -aux=decls | grep decl_text && run_aux -json -aux=types | grep hash && run_aux -json -aux=asts | grep body
