#!/bin/bash
#
# If -aux is provided, the default AuxDB entries do not
# end up in the output.
#
. $(dirname $0)/common

run_aux -json -aux=types | grep -v decl_text && run_aux -json -aux=decls | grep -v hash
