#!/bin/bash

SCRIPT="$0"
describe(){
    local DESCRIPTION=$(cat "$SCRIPT" \
        |sed '/^[^#]/q' \
        |head -n -1 \
        |tail -n +3 \
        |sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' \
        |cut -c3- \
        |sed 's/^/  /')
    echo "$DESCRIPTION"
    exit 0; }
if [ ! -z "$1" ] &&
   $(echo "$1"|grep -q "^\-d$");then describe; fi

PATH=third-party/jshon:$PATH
HELLO=etc/hello.c
HELLO_EXE=etc/hello
HELLO_LLVM_IR=etc/hello.ll

DECLS=etc/decls.c

POUND_DEF=etc/pound-define-func.c
POUND_DEF_STRUCT=etc/pound-define-struct.c
TYPEDEF_TYPE_HASH=etc/typedef-type-hash.c

MACROS=etc/macros.c

MACROS2=etc/macros2.c

AUX=etc/aux.c

LIST=etc/list.c

NULLC=etc/null.c

SCOPES=etc/scopes.c

GCD=etc/gcd-wo-curlies.c

IF=etc/if.c

MORE_LOOPS=etc/more-loops.c

ARRAY_LIST=etc/array_list.c

MUSE_LIST=etc/muse_list.c

SWITCH=etc/switch.c

CLASS=etc/class.cpp

MULTIDIMENSIONAL_ARRAY=etc/multidimensional_array.c

DO_LOOP_NON_COMPOUND_BODY=etc/do-loop-non-compound-body.c

FOR_LOOP_NON_COMPOUND_BODY=etc/for-loop-non-compound-body.c

WHILE_LOOP_NON_COMPOUND_BODY=etc/while-loop-non-compound-body.c

IF_NON_COMPOUND_BODY=etc/if-non-compound-body.c

GLOBAL_VAR=etc/global_var.c

ARRAY_OF_PTRS=etc/array_of_pointers.c

PTR_TO_ARRAY=etc/pointer_to_array.c

TYPEDEF=etc/typedef.c

ARRAY_INITIALIZER=etc/array-initializer.c

ARROW_OPERATOR=etc/arrow-operator.cpp

TYPES=etc/types.c

GLOBAL_VARS_SYN_CTX=etc/global-vars-syn-ctx.c

POINTERS_TO_POINTERS=etc/pointers-to-pointers.c

STRUCT_IN_SYS_HEADER=etc/struct-in-sys-header.c

FUNCTION_IN_SYS_HEADER=etc/function-in-sys-header.c

FUNCTION_IN_USER_HEADER=etc/function-in-user-header.c

SQRT=etc/sqrt.c

OPEN=etc/open.c

MACRO_WITH_VAR_DECL=etc/macro_with_var_decl.c

MACRO_WITH_MULTIVAR_DECL=etc/macro_with_multivar_decl.c

CONST_VAR=etc/const_var.c

VOLATILE_VAR=etc/volatile_var.c

RESTRICT_VAR=etc/restrict_var.c

FUNCTION_POINTER=etc/function_pointer.c

FUNCTION_POINTER_NO_PROTO=etc/function_pointer_no_proto.c

INT64_T=etc/int64_t.c

ALLOCA_MACRO=etc/alloca_macro.c

STORAGE_CLASSES=etc/storage_classes.c

FUNCTION_WITH_ATTRIBUTE_MACRO=etc/function-with-attribute-macro.c

run_hello(){
    clang-mutate "$@" $HELLO --; }

run_decls(){
    clang-mutate "$@" $DECLS --; }

run_typedef_type_hash_test(){
    clang-mutate "$@" $TYPEDEF_TYPE_HASH --; }

run_pound_define_struct(){
    clang-mutate "$@" $POUND_DEF_STRUCT --; }

run_pound_define(){
    clang-mutate "$@" $POUND_DEF --; }

run_macros(){
    clang-mutate "$@" $MACROS --; }

run_macros2(){
    clang-mutate "$@" $MACROS2 --; }

run_aux(){
    clang-mutate "$@" $AUX --; }

run_list(){
    clang-mutate "$@" $LIST --; }

run_null(){
    clang-mutate "$@" $NULLC --; }

run_scopes(){
    clang-mutate "$@" $SCOPES --; }

run_gcd(){
    clang-mutate "$@" $GCD --; }

run_if(){
    clang-mutate "$@" $IF --; }

run_array_list(){
    clang-mutate "$@" $ARRAY_LIST --; }

run_more_loops(){
    clang-mutate "$@" $MORE_LOOPS --; }

run_muse_list(){
    clang-mutate "$@" $MUSE_LIST --; }

run_switch(){
    clang-mutate "$@" $SWITCH --; }

run_class(){
    clang-mutate "$@" $CLASS --; }

run_multidimensional_array(){
    clang-mutate "$@" $MULTIDIMENSIONAL_ARRAY --; }

run_array_of_pointers(){
    clang-mutate "$@" $ARRAY_OF_PTRS --; }

run_pointer_to_array(){
    clang-mutate "$@" $PTR_TO_ARRAY --; }

run_do_loop_non_compound_body() {
    clang-mutate "$@" $DO_LOOP_NON_COMPOUND_BODY --; }

run_for_loop_non_compound_body(){
    clang-mutate "$@" $FOR_LOOP_NON_COMPOUND_BODY --; }

run_while_loop_non_compound_body() {
    clang-mutate "$@" $WHILE_LOOP_NON_COMPOUND_BODY --; }

run_if_non_compound_body() {
    clang-mutate "$@" $IF_NON_COMPOUND_BODY --; }

run_global_var(){
    clang-mutate "$@" $GLOBAL_VAR --; }

run_typedef(){
    clang-mutate "$@" $TYPEDEF --; }

run_array_initializer(){
    clang-mutate "$@" $ARRAY_INITIALIZER --; }

run_arrow_operator(){
    clang-mutate "$@" $ARROW_OPERATOR --; }

run_types(){
    clang-mutate "$@" $TYPES --; }

run_global_vars_syn_ctx(){
    clang-mutate "$@" $GLOBAL_VARS_SYN_CTX --; }

run_pointers_to_pointers(){
    clang-mutate "$@" $POINTERS_TO_POINTERS --; }

run_struct_in_sys_header(){
    clang-mutate "$@" $STRUCT_IN_SYS_HEADER --; }

run_function_in_sys_header(){
    clang-mutate "$@" $FUNCTION_IN_SYS_HEADER --; }

run_function_in_user_header(){
    clang-mutate "$@" $FUNCTION_IN_USER_HEADER -- -c; }

run_sqrt() {
    clang-mutate "$@" $SQRT --; }

run_open() {
    clang-mutate "$@" $OPEN --; }

run_macro_with_var_decl() {
    clang-mutate "$@" $MACRO_WITH_VAR_DECL --; }

run_macro_with_multivar_decl() {
    clang-mutate "$@" $MACRO_WITH_MULTIVAR_DECL --; }

run_const_var() {
    clang-mutate "$@" $CONST_VAR -- -c; }

run_volatile_var() {
    clang-mutate "$@" $VOLATILE_VAR -- -c; }

run_restrict_var() {
    clang-mutate "$@" $RESTRICT_VAR -- -c; }

run_function_pointer() {
    clang-mutate "$@" $FUNCTION_POINTER --; }

run_function_pointer_no_proto() {
    clang-mutate "$@" $FUNCTION_POINTER_NO_PROTO --; }

run_int64_t() {
    clang-mutate "$@" $INT64_T --; }

run_alloca_macro() {
    clang-mutate "$@" $ALLOCA_MACRO --; }

run_storage_classes() {
    clang-mutate "$@" $STORAGE_CLASSES --; }

run_function_with_attribute_macro() {
    clang-mutate "$@" $FUNCTION_WITH_ATTRIBUTE_MACRO -- -c; }

json() {
    cat -|jshon "$@"; }

json_filter(){
    cat -|jshon -a -j|grep "\"${1}\":${2}\(,\|}\)"; }

with_src_text(){
    cat -|jshon -a -j|grep "\"src_text\":\"${1}\"\(,\|}\)"; }

json_key_filter(){
    cat -|jshon -a -j|grep "\"${1}\":"; }

# Wrap lines of json objects into a json array.
json_wrap(){
    echo "["
    cat -|sed '$ ! s/$/,/'
    echo "]"; }

# Check if the jshon input has the expected length.
json_has_length(){
    if [ ! $(cat -|jshon -l) -eq $1 ];then
        exit 1;
    fi
}

inserted(){
    wdiff $HELLO <(cat -)|grep "{\+.*\+}"|sed 's/^.*{+//;s/+}.*$//'; }

cuted(){
    wdiff $HELLO <(cat -)|grep "\[-.*-\]"|sed 's/^.*\[-//;s/-\].*$//'; }

contains(){
    if [ ! $? -eq 0 ];then exit 1;fi
    BASE="$1"; shift;
    for TARGET in "$@";do
        if ! $(echo "$BASE"|grep -- "$TARGET" >/dev/null 2>/dev/null);then
            echo "missing \"$TARGET\""
            exit 1;
        fi
    done; }

not_contains(){
    if [ ! $? -eq 0 ];then exit 1;fi
    BASE="$1"; shift;
    for TARGET in "$@";do
        if $(echo "$BASE"|grep -- "$TARGET" >/dev/null 2>/dev/null);then
            exit 1;
        fi
    done; }

equals() {
    if [ ! "$1" == "$2" ]; then
        echo "\"$1\" != \"$2\""
        exit 1;
    fi }
