#!/bin/bash
#
# Test to ensure that CXXMethod decls have a body field.
. $(dirname $0)/common

full=$(run_class -json|json_filter class "\"CompoundStmt\""|json_wrap|
              json -a -e full_stmt)
not_contains "$full" "false"
