#!/bin/bash
#
# Test to ensure that non-CompoundStatement do loop bodies are full statements
. $(dirname $0)/common

full=$(run_do_loop_non_compound_body -json|
       json_filter class "\"CallExpr\""|
       json_wrap|
       json -a -e full_stmt)

not_contains "$full" "false"
