#!/bin/bash
#
# Ensure a function pointer is found
. $(dirname $0)/common

type=$(run_function_pointer -json |
       json_filter name "\"int (int, char.*)\"" |
       json_wrap |
       json_filter pointer "true" |
       jshon -e hash)

[ $type != "" ]
