#!/bin/bash
# Test function is a top level systax

. $(dirname $0)/common

syn_ctx=$(clang-mutate ${MUSE_LIST} -json -- \
              |json_filter name "\"AddNode"\" \
              |json -e syn_ctx)

if [ $syn_ctx == "\"TopLevel\"" ];then
    exit 0;
else
    exit 1;
fi
