#!/bin/bash
#
# Ensure swap of two full statements preserves semi colons.
#
. $(dirname $0)/common

contains "$(run_hello -swap -stmt1=5 -stmt2=11)" \
         "return 0;" \
         "puts(\"hello\");"
