#!/bin/bash
# Test the default fields are present when nothing is specified
# for -fields
. $(dirname $0)/common

run_hello -json -llvm_ir=${HELLO_LLVM_IR}|json_filter llvm_ir ".*" \
    |json_wrap|json_has_length 4
