#!/bin/bash
# Test the specified fields are present when values are passed
# via -fields.
. $(dirname $0)/common

contains "$(run_hello -json -stmt1=12 -fields="class,unbound_vals"| json)" \
         '"class": "IntegerLiteral"' \
         '"unbound_vals": \[]' 

if [ $? -eq 0 ]; then
    not_contains "$(run_hello -json -stmt1=12 -fields="class,unbound_vals"| json)" \
                 '"counter"' 
fi
