#!/bin/bash
#
# We don't want to include semicolons in statements in json output
# because we might later want to insert the statement *within* another
# statement.  E.g., "x++" could be a ;-terminated full statement in
# the original program, but may reasonably be inserted as a variable
# index.
#
. $(dirname $0)/common

run_hello -json|json_filter counter 2|jshon -e src_text -u|grep -vq ";$"
