#!/bin/bash
# Test the default fields are present when nothing is specified
# for -fields
. $(dirname $0)/common

contains "$(run_hello -json -stmt1=12 | json)" \
         '"src_file_name":.*,' \
         '"ast_class": "IntegerLiteral"' \
         '"unbound_vals": \[]' \
         '"begin_src_col": 10' \
         '"begin_src_line": 5' \
         '"counter": 12' \
         '"end_src_col": 10' \
         '"full_stmt": false' \
         '"end_src_line": 5' \
         '"guard_stmt": false' \
         '"macros": \[]' \
         '"parent_counter": 11' \
         '"src_text": "0"' \
         '"types": \[]' \
         '"unbound_funs": \[]'
