#!/bin/bash
. $(dirname $0)/common

contains "$(run_hello -set2 \
                         -stmt1=11 -value1="puts(\"goodbye 2\")" \
                         -stmt2=5 -value2="puts(\"goodbye 1\")")" \
         "goodbye 2\");" \
         "goodbye 1\");"
