#!/bin/bash
#
# We don't want to include semicolons in statements text because we
# might later want to insert the statement *within* another statement.
# E.g., "x++" could be a ;-terminated full statement in the original
# program, but may reasonably be inserted as a variable index.
#
. $(dirname $0)/common

run_hello -get -stmt1=2|grep -vq ";$"
