#!/bin/bash
# Test the default fields are present when nothing is specified
# for -fields
. $(dirname $0)/common

RAW="$(run_hello -json|json -a -e counter)"

diff <(echo "$RAW") <(echo "$RAW"|sort -n)
