#!/bin/bash
#
# Ensure that we can extract a long macro definition
#
. $(dirname $0)/common

long_macro="$(run_macros -json |
              json_filter hash -2769171426394948104 |
              json -e name)"

equals $long_macro "\"LONG_MACRO\""
