#!/bin/bash
#
# Test to ensure that multi-dimensional array decls have a type
. $(dirname $0)/common

types=$(run_multidimensional_array -json |
        json_filter ast_class "\"DeclStmt\"" |
        json_wrap |
        jshon -a -e types)
not_contains "$types" "[]"
