#!/bin/bash
#
# Test to ensure that multi-dimensional array decls have a type
. $(dirname $0)/common

types=$(run_multidimensional_array -json |
        json_filter class "\"DeclStmt\"" |
        json_wrap |
        json -a -e types)
not_contains "$types" "[]"
