#!/bin/bash
#
# Test to ensure that the type of a pointer to an array
# is parsed correctly
. $(dirname $0)/common

num_types=$(run_pointer_to_array -json |
        json_filter ast_class "\"DeclStmt\"" |
        json -e types |
        json -l)

if [ ${num_types} -eq 1 ]; then
    exit 0
else
    exit 1
fi

