#!/bin/bash
#
# Replacing the "then" block of an if with a single statement (no
# curlies) should keep the curly braces.
#
. $(dirname $0)/common

contains "$(run_if -set -stmt1=12 -value1="x = 1;")" "{x = 1;}"
