#!/bin/bash
#
# Test that function args are in a local scope.
#
. $(dirname $0)/common

OUTPUT=$(run_scopes -json | json_filter counter 9)

contains $(echo $OUTPUT | json -e scopes -e 2 -e 0) \
         "funarg"
contains $(echo $OUTPUT | json -C -e scopes -e 3 -e 0) \
         "global"
