#!/bin/bash
#
# Ensure that we can extract a short macro definition.
#
. $(dirname $0)/common

short_macro="$(run_macros -json |
               json_filter hash -1038532117783754115 |
               json -e name)"

equals $short_macro "\"SHORT_MACRO\""
