#!/bin/bash
#
# Ensure all ASTs within the macro expansion have the same ending offset.
. $(dirname $0)/common

end_off=$(run_strcmp_macro -json |
          json_filter in_macro_expansion "true" |
          json_wrap |
          json -a -e end_off |
          tr " " "\n" |
          sort -u)

equals "90" $end_off
