#!/bin/bash
#
# Test if type field in the body has the hash value
#
. $(dirname $0)/common

type_hash=$(clang-mutate ${MUSE_LIST} -json -- \
                |json_filter name "\"LIST"\"   \
                |json -e hash)

# This types list should include the type found above.
arg=$(clang-mutate ${MUSE_LIST} -json --  \
          |json_filter name "\"AddNode"\" \
          |json -e types -a -j)

contains "$arg" "$type_hash"
