#!/bin/bash
# Test Function return has valid hash value

. $(dirname $0)/common

type_hash=$(clang-mutate ../etc/muse_list.c -json -- | json_filter type "\"LISTNODE"\" | jshon -e hash)


ret=$(clang-mutate ../etc/muse_list.c -json -- | json_filter name "\"AddNode"\" | jshon -e ret)

if [ ! $ret == $type_hash ]; then
    exit 1;
fi
