#!/bin/bash
# Test Type has name and a hash value

. $(dirname $0)/common

type_hash=$(clang-mutate ${MUSE_LIST} -json -- \
                |json_filter type "\"LIST"\"   \
                |json -e hash)

if [ -z $type_hash ]; then
    exit 1
else
    exit 0
fi
