#!/bin/bash
# Test Function return has valid hash value

. $(dirname $0)/common

type_hash=$(clang-mutate ${MUSE_LIST} -json -- | json_filter name "\"LISTNODE"\" | json -e hash)


ret=$(clang-mutate ${MUSE_LIST} -json -- | json_filter name "\"AddNode"\" | json -e ret)

if [ ! $ret == $type_hash ]; then
    exit 1;
fi
