#!/bin/bash
# Test if the function argument the hash value
. $(dirname $0)/common

TYPE_HASH=$(clang-mutate ${MUSE_LIST} -json -- \
                |json_filter type "\"LIST"\"   \
                |jshon -e hash)

ARG=$(clang-mutate ${MUSE_LIST} -json --  \
          |json_filter name "\"AddNode"\" \
          |jshon -e types)

contains "${ARG}" ${TYPE_HASH}
