#!/bin/bash
#
# Test to ensure that non-CompoundStatement while loop bodies
# are full statements
. $(dirname $0)/common

full=$(run_while_loop_non_compound_body -json|
       json_filter ast_class "\"CallExpr\""|
       json_wrap|
       json -a -e full_stmt)

not_contains "$full" "false"
