#!/bin/bash
#
# Wrapping the then branch in a compound statement should *not* place
# a semicolon after the compound statement (it breaks the if).
#
. $(dirname $0)/common

! run_if -set -stmt1=25 -value1="{ x = 1; }" | grep "{ x = 1; };"
