variables:
  DOCKER_REGISTRY: "docker.grammatech.com"
  LOCAL_IMAGE_NAME: '$CI_PROJECT_PATH-$CI_PIPELINE_ID-$CI_BUILD_REF_NAME'

stages:
  - build-test-and-tag
  - dependents

.run-template: &run
  script:
    - if [ "$OS" = "ubuntu" ];
      then
          docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY;
          docker pull $DOCKER_REGISTRY/synthesis/clang:latest;
      elif [ "$OS" = "arch" ];
      then
          docker pull base/archlinux;
      fi

    - cat Dockerfile.$OS|sed "s/CI_COMMIT_SHA/$CI_COMMIT_SHA/" > Dockerfile
    - docker build -f Dockerfile -t ${LOCAL_IMAGE_NAME}-${OS} .

    # If on master branch, push test results to DataManager and push
    # up a new "latest" image, otherwise, run locally.
    - if [ "$CI_BUILD_REF_NAME" = "master" ];
      then
          if [ "$OS" = "ubuntu" ];
          then
              docker run -e LOCAL_USER=root ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/clang-mutate && make check-testbot";
              docker tag ${LOCAL_IMAGE_NAME}-${OS} $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest;
              docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY;
              docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest;
          elif [ "$OS" = "arch" ];
          then
              docker run -e LOCAL_USER=root ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/clang-mutate && make check-testbot";
              docker tag ${LOCAL_IMAGE_NAME}-${OS} $DOCKER_REGISTRY/$CI_PROJECT_PATH:arch;
              docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY;
              docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:arch;
          else
              docker run -e LOCAL_USER=root ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/clang-mutate && make check";
          fi
      else
          docker run -e LOCAL_USER=root ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/clang-mutate && make check";
      fi

    # Cleanup
    - docker rmi -f ${LOCAL_IMAGE_NAME}-${OS}

run-ubuntu:
  stage: build-test-and-tag
  variables:
    OS: 'ubuntu'
  <<: *run

run-arch:
  stage: build-test-and-tag
  variables:
    OS: 'arch'
  <<: *run

trigger_java_mutator:
  stage: dependents
  script:
    - "curl -X POST -F token=ae9cfaeb981e605a4244c783f30b55 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/376/trigger/pipeline"
  only:
    - master
