FROM docker.grammatech.com:14850/synthesis/clang

RUN apt-get -y update && \
    apt-get -y install wdiff libtinfo-dev libz-dev libxcb1-dev pandoc

ARG GT
COPY . /gt/clang-mutate

RUN cd /gt/clang-mutate/ && \
    git checkout CI_COMMIT_SHA && \
    make -j4 clang-mutate && \
    make install

WORKDIR /gt/clang-mutate

CMD /bin/bash
