#include "GTDockerConfig.h"
#include "GTClangMutateConfig.h"

FROM __GTD__MAKE_FROM(synthesis/clang)

RUN apt_deps=__GTD__CLANG_MUTATE_APT_DEPS && \
    apt-get -y update && apt-get -y install ${apt_deps}

RUN mkdir -p __GTD__PATH_CLANG_MUTATE_HOME && \
    git clone git@git.grammatech.com:synthesis/clang-mutate.git __GTD__PATH_CLANG_MUTATE_HOME && \
    cd __GTD__PATH_CLANG_MUTATE_HOME && \
    make -j4 clang-mutate && \
    make install

WORKDIR __GTD__PATH_GT_ROOT

CMD /bin/bash
